### ISSUE TITLE
안녕하세요 여쭤볼 게 있습니다 ㅎㅎ!

### ISSUE THREAD

**Issue by yulhee741** [JunHyeok96/Road-Segmentation#2]
안녕하세요, 저번에 메일 한번 드렸던 학생입니다.
다름이 아니라, demo.py에서 영상을 입력받고 모델이 예측하는 코드에서 궁금한 점이 생겨 질문드립니다.
제가 이미지를 입력받고  보행로 이미지를 예측하는 코드를 짜보고 싶은데요,
demo 코드에서 frame2가 어떤건지 이해가 잘 가지 않습니다.
모델이 예측한 pre를 print 해봤을 때 배열이 나오던데 이 배열이 혹시 뭔지 알려주실 수 있을까요?
그리고 create_mask()함수의 결과물인 pre를 활용해서 frame2(pre==1)이 부분이 라벨을 분류하는 코드일까요??
답변 주시면 정말 감사하겠습니다.
좋은 하루 되시기 바랍니다 ^^!

**Comment by JunHyeok96** [comment]
```python
pre = model.predict(frame) #모델 예측
pre = create_mask(pre).numpy() #예측 값 중 각 픽셀에 대해 argmax(픽셀 별로 가능 높은 확률로 classify하는 과정입니다)

#결과 영상을 만들기 위한 작업
frame2 = frame/2  #기존 영상에서 절반으로 나누는 이유는 밝기를 줄이기 위해서 입니다. 
frame2[0][(pre==1).all(axis=2)] += [0, 0, 0] #""bike_lane_normal", "sidewalk_asphalt", "sidewalk_urethane""
frame2[0][(pre==2).all(axis=2)] += [0.5, 0.5,0] # "caution_zone_stairs", "caution_zone_manhole", "caution_zone_tree_zone", "caution_zone_grating", "caution_zone_repair_zone"]
frame2[0][(pre==3).all(axis=2)] += [0.2, 0.7, 0.5] #"alley_crosswalk","roadway_crosswalk"
frame2[0][(pre==4).all(axis=2)] += [0, 0.5, 0.5] #"braille_guide_blocks_normal", "braille_guide_blocks_damaged"
frame2[0][(pre==5).all(axis=2)] += [0, 0, 0.5] #"roadway_normal","alley_normal","alley_speed_bump", "alley_damaged""
frame2[0][(pre==6).all(axis=2)] += [0.5, 0, 0] #"sidewalk_blocks","sidewalk_cement" , "sidewalk_soil_stone", "sidewalk_damaged","sidewalk_other"
```
segmentation은 픽셀 별로 가장 높은 확률의 object로 분류합니다. 가령 인도, 차도, 자전거 도로로 나눠져있다고하면 [0.7, 0.2, 0.3]의 배열의 형태로 추론되고 argmax를 통해 이중 값이 가장 높은(0.7) 인도로 해당 픽셀의 결과가 결정됩니다. 

frame2(pre==1)부분은 말씀하신대로 1번으로 분류된 픽셀만 선정하기 위해 작성된 코드입니다. 이 작업을 한 이유는 분류된 픽셀별로 다른 색으로 영상에 나타내기 위해서 입니다. 감사합니다.

**Comment by yulhee741** [comment]
빠른 답변 정말 감사합니다 ㅠㅠ!
친절하게 답변해주셔서 도움이 될 거 같습니다. 정말 감사합니다
좋은 하루 되시기 바랍니다 ☺️
